// All tokens verified live against the Greenhouse boards API. The registry +
// discovery grow this set further over time.
export const DEFAULT_GREENHOUSE_BOARD_TOKENS = [
  'stripe',
  'affirm',
  'brex',
  'gusto',
  'datadog',
  'figma',
  'airtable',
  'asana',
  'mongodb',
  'cloudflare',
  'robinhood',
  'reddit',
  'duolingo',
  'samsara',
  'twilio',
  // Verified additions
  'airbnb',
  'dropbox',
  'lyft',
  'instacart',
  'coinbase',
  'databricks',
  'gitlab',
  'discord',
  'pinterest',
  'sofi',
  'chime',
  'webflow',
  'vercel',
  'mixpanel',
  'amplitude',
  'faire',
  'scaleai',
  'calm',
  'flexport',
  'gemini',
  // Verified additions - non-tech industries (health, retail/consumer, food
  // logistics, education), so the registry isn't biased toward tech/fintech.
  'komodohealth',
  'flatironhealth',
  'classpass',
  'peloton',
  'squarespace',
  'lattice',
  'remotecom',
  'hellofresh',
  'glossier',
  'bombas',
  'everlane',
  'reformation',
  'stitchfix',
  'stockx',
  'khanacademy',
  'coursera',
  'udemy',
  'udacity',
  '2u',
  'outschool',
  'masterclass',
  'guild',
];

export const DEFAULT_GREENHOUSE_BOARDS = DEFAULT_GREENHOUSE_BOARD_TOKENS.map((token) => ({
  token,
  source: 'seed',
}));
